# Generated by Django 4.2.4 on 2023-08-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='short_urls',
            new_name='ShortUrls',
        ),
    ]
